# Permalinks
permalink:        pretty
highlighter: rouge
markdown: kramdown

# Setup
title:            Gary's Blog
tagline:          The painter
url:              http://gary1992.com
paginate:         5
baseurl:          /
author:
  name:           Gary Lyn
  url:            http://www.weibo.com/u/1354300893/
  email:          liues1992@163.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/liues1992/liues1992.github.io

# Gems
gems: [jekyll-paginate]